"""Stable error codes used by mcp-docs-toolkit JSON output."""

CONFIG_MISSING = "CONFIG_MISSING"
CONFIG_INVALID = "CONFIG_INVALID"
AUTH_FAILED = "AUTH_FAILED"
NETWORK_ERROR = "NETWORK_ERROR"
NOT_IMPLEMENTED = "NOT_IMPLEMENTED"
DOWNLOAD_WRITE_FAILED = "DOWNLOAD_WRITE_FAILED"
